safe: false
auto: true
server: true
server_port: 8080
source: .
destination: ../../build/static
markdown: kramdown
permalink: /news/:year/:month/:day/:title.html
custom:
  downloads:
    editor-url-prefix: "https://storage.googleapis.com/dart-editor-archive"
    dartium-url-prefix: "https://storage.googleapis.com/dartium-archive"
    binaries:
      - os: win32
        name: Windows
        ext: zip
        editor-ext: zip
      - os: macos
        name: Mac
        ext: zip
        editor-ext: zip
      - os: linux
        name: Linux
        ext: tar.gz
        editor-ext: zip
kramdown:
  toc_levels: [2,3]